### ISSUE TITLE
Beam Number Tracking in plan.Trial File

### ISSUE THREAD

**Issue by lswootton** [AndrewWAlexander/Pinnacle-tar-DICOM#1]
Script will incorrectly track beam number while reading plan.Trial file if 'ProtonBeam ={};' is included in the plan file, which is the case for our Institution (Pinnacle 9.10), resulting in using list indices greater than the length of the beam list causing the program to crash.

**Comment by AndrewWAlexander** [comment]
Hi 

Thanks for the contribution! I've looked at your fix and will push it to the main source code.

**Comment by AndrewWAlexander** [comment]
Hi Iswootton, 
I assume this issue can be closed now.
