### ISSUE TITLE
Pixel Data difference 

### ISSUE THREAD

**Issue by ArthurRochette** [AndrewWAlexander/Pinnacle-tar-DICOM#18]
I got a strange operation going on. I got the original Dicom files of my pinnacle (Pinnacle 9.10) patient.
When I compare the two pixel data tags (of the original dicom and the one from the script) there is a significant difference (close to 90% of differences). My Dose Grid Scaling tags are identicals. 
I don't know if this is from Pinnacle 9.10, if you have any clue :)

**Comment by crcrewso** [comment]
Could you try using [the pymedphys updated version of this tool](https://docs.pymedphys.com/en/latest/users/ref/cli/pinnacle.html). It has a number of patches and updates.
