### ISSUE TITLE
Prone patient question

### ISSUE THREAD

**Issue by nkumar228** [AndrewWAlexander/Pinnacle-tar-DICOM#3]
Hi Andrew,
Thanks so much for the script. It has been of great help, especially since our actual Pinnacle hardware is now dead.  I am an amateur coder to say the least.  I created a front end file that allows specify a folder of .tar files, unzip them and export them to a specified folder.  I played with the script and have gotten the supine dose to work for all of our versions of Pinnacle (at the expense of the ROIs which we can't import into Raystation anyway). But when I moved to HFP, the data set comes out fine, but the RTDOSE file is rotated S-I.  Any idea why that might be happening?  I have included my modified code.  Thanks!

[CreateDICOMDose.zip](https://github.com/AndrewWAlexander/Pinnacle-tar-DICOM/files/1623804/CreateDICOMDose.zip)

**Comment by AndrewWAlexander** [comment]
That is great news that the script has been helpful to you. I cannot confirm if I have tested all patient orientations, so I suspect that you have uncovered a real bug. It should be easy enough to fix, but I might need a test data-set to work with. I'll see what I can do without any test data first.

**Comment by AndrewWAlexander** [comment]
I just confirmed that I can import a FFP patient into Eclipse version 11 without any noticeable issue. I will try and import a HFP patient next.

**Comment by AndrewWAlexander** [comment]
I tested a HFP patient today. The script seems to work fine for HFP patients. There are some minor dose differences  observed in the dose distribution, but overall structures, plan, and dose is displayed in the correct orientation for HFP. 

The image below is compares the HFP plan exported directly from Pinnacle and the DICOM files generated by this script. 

![aa](https://user-images.githubusercontent.com/16063425/42716588-78d6cfb6-86b9-11e8-91e2-2adddce04699.png)
