### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by willbur209** [AndrewWAlexander/Pinnacle-tar-DICOM#4]
Hello,

Having some issues running your script. Do you have some setup instructions or example?

**Comment by pchlap** [comment]
Hi,

did you see the guide in the Wiki? https://github.com/AndrewWAlexander/Pinnacle-tar-DICOM/wiki/Running-the-code :)

Cheers
Phil

**Comment by willbur209** [comment]
Wow sorry I missed that. Do you know if this is for python 2 or python 3? I was having some issues with import pydicom in python 3. Another user uploaded his code that looks like it uses pydciom. Do you support that?

Thanks!

Will

**Comment by pchlap** [comment]
You will definitely require pydicom to run the script :) I believe the script works only with python 3, but can be modified pretty easily to work with python 2 (by taking out the encoding parameter from the calls to open()).

Phil

**Comment by AndrewWAlexander** [comment]
Hi Will and pchlap,
Thanks for giving this code a look over. I did not include the python version in the wiki. I'll update that.
