### ISSUE TITLE
MU Calculation

### ISSUE THREAD

**Issue by rechlalef** [AndrewWAlexander/Pinnacle-tar-DICOM#6]
Hi Andrew,

As we discuss, we need to introduce the OFc value in the MU Calculation: 
`OFc = float(re.findall(r"[-+]?\d*\.\d+|\d+", all_lines[linenum + 17])[0])` 
and the MU calculation becomes:
`beammu = float(re.findall(r"[-+]?\d*\.\d+|\d+", line)[0])/(normdose*PDD6MV*OFc)`

Thanks again for this code :)

**Comment by AndrewWAlexander** [comment]
Thanks for tweaking the MU calculation! I have added these lines to the code.

**Comment by AndrewWAlexander** [comment]
commit d59b7da8384a906e91ddb0cd4ef64bc445df6872 closes #6
