### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by lucserre** [AndrewWAlexander/Pinnacle-tar-DICOM#8]
Hi - sorry to include this in "issues" but I can't seem to find information on HOW to use this.
I've got python all setup and working, but not sure how to use this since "python createDICOM.py" returns a blank line.
Thanks.

**Comment by simonfoschepoth** [comment]
I think it is a good question! 
I'm at the same Point and planned to study the source code until I understand how to use it. I couldn't invest much time until now ( for the initial old Patient case I wanted to recover by this, I was too slow anyway) but plan to try it out as soon as I find the time.

Thank you very much for sharing this script and thank you even more if you find the time to write a small instruction to use.

best regards

Simon

**Comment by AndrewWAlexander** [comment]
Sorry for the slow reply to both of you. I placed a guide in the Wiki.

https://github.com/AndrewWAlexander/Pinnacle-tar-DICOM/wiki/Running-the-code

**Comment by simonfoschepoth** [comment]
Thank you very much, this will be really helpful! After putting so much effort in the script you have every right to take all the time you need or even simply ignore us ;-) Thank you for taking the time to explain something, which probably is quite obvious for many People out there.
